blog/urls.py
from django.urls import path

from .views import posts, post_detail


urlpatterns = [
    path('', posts, name='posts'),
    path('post_detail/', post_detail, name='post_detail'),
]

carts/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.cart, name='cart'),
    path('update/', views.update_cart_item, name='update_cart_item'),
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    
]

ecommerce_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path



urlpatterns = [

    # Admin urls 
    path('admin/', admin.site.urls),

    # account
    path('accounts/', include('allauth.urls')),

    # # users app
    # path('users/', include('users.urls')), # new
    # path('users/', include('django.contrib.auth.urls')),

    # products app urls
    path('', include('products.urls')),
    
    # carts app url
    path('cart/', include('carts.urls')),

    # orders app urls
    path('order/', include('orders.urls')),

    # directOrders app urls
    path('direct_order/', include('directOrders.urls')),

    # blog app
    path('blog/', include('blog.urls')),

    # ckeditor file upload
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    
]

# Load static files in local development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carts/models.py
from django.db import models

from products.models import Product

# Create your models here.
class CartItem(models.Model):
    cart = models.ForeignKey('cart', on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.CharField(max_length=50, null=True, blank=True)
    type = models.CharField(max_length=50, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(max_digits=100, decimal_places=2, default=10.00)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.product.title
    


class Cart(models.Model):
    total = models.DecimalField(max_digits=100, decimal_places=2, default=10.00)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "Cart id: %s" %(self.id)
    

carts/views.py
''' Contains all the cart view.'''

from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse

from products.models import Product
from .models import Cart, CartItem
from .view_helper_functions import retrived_product,retrived_cart, update_cart_total, update_cartitem


def cart(request):
    '''Get the cart id from the session, retrive the cart
    from the database and then pass it to the context dict.'''

    # retrive cart from session, making context, render
    try:
        the_id = request.session['cart_id']
    except:
        the_id = None
    
    if the_id:
        cart = Cart.objects.get(id=the_id)
        context = {'cart': cart}
    else:
        context = {'empty': True}
    
    template = 'carts/cart.html'
    return render(request, template, context)


def add_to_cart(request, slug):
    '''Retrive the product and the cart then feed to the
    CartItem.Then update the cartitem and the cart.'''

    # retrive the product
    product = retrived_product(slug)
    
    # retrive the cart
    cart = retrived_cart(request)

    # Feeding to the CartItem
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    
    # update cartitem and cart
    update_cartitem(request, cart_item)
    update_cart_total(request, cart)

    return HttpResponseRedirect(reverse('cart'))


def remove_from_cart(request, pk):

    cart = retrived_cart(request)
    cart_item = CartItem.objects.filter(cart=cart, pk=pk)
    cart_item.delete()
    # message
    update_cart_total(request, cart)
    
    return HttpResponseRedirect(reverse('cart'))



def update_cart_item(request):
    '''Update cart Item quantity and also variations(still not applied) from the cart.'''

    
    pk = request.GET.get('pk')
    cart_item = CartItem.objects.get(pk=pk)

    if int(request.GET.get('qty')) <= 0:
        cart_item.delete()
        cart = retrived_cart(request)
        update_cart_total(request, cart)
        cart_total = cart.total
        return JsonResponse({
            'id': pk,
            'product': 'empty',
            'cart_total': cart_total
        })
        
    cart_item.quantity = request.GET.get('qty')
    cart_item.save()
    cart = retrived_cart(request)
    update_cart_total(request, cart)

    if request.is_ajax():
        line_total = CartItem.objects.get(pk=pk).line_total
        cart_total = cart.total
        print('hi')
        return JsonResponse({
            'line_total': line_total,
            'cart_total': cart_total
        })
    
    return HttpResponseRedirect(reverse('cart'))

templates/carts/cart.html
{% extends 'bases/base.html' %}
{% load static %}
{% block content %}
    {% if not empty or not cart.caritem_set.all %}
    <!-- Hero Section-->
    <section class="hero">
      <div class="container">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb justify-content-center">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item active">Shopping cart        </li>
        </ol>

        <!-- Hero Content-->
        <div class="hero-content pb-5 text-center">
          <h1 class="hero-heading">Shopping cart</h1>
          <div class="row">   
            <div class="col-xl-8 offset-xl-2">
                <p class="lead text-muted">You have {{cart.cartitem_set.all.count }} items in your shopping cart</p>
            </div>
          </div>
        </div>

      </div>
    </section>
    <!-- Shopping Cart Section-->
    
    <section>
      <div class="container">
        <div class="row mb-5"> 
          <div class="col-lg-8">
            <div class="cart">
              <div class="cart-wrapper">
                <div class="cart-header text-center">
                  <div class="row">
                    <div class="col-5">Item</div>
                    <div class="col-2">Price</div>
                    <div class="col-2">Quantity</div>
                    <div class="col-2">Total</div>
                    <div class="col-1"></div>
                  </div>
                </div>
                <div class="cart-body">
                {% comment %} Showing all the cart items {% endcomment %}
                {% for item in cart.cartitem_set.all %}
                  <!-- Product-->
                  <div class="cart-item" id='item-{{ item.id }}'>
                    <div class="row d-flex align-items-center text-center">
                      <div class="col-5">
                        <div class="d-flex align-items-center">
                          <a href="{% url 'detail' item.product.slug %}">
                            <img src="{{item.product.get_image_url }}" alt="..." class="cart-item-img">
                          </a>
                          <div class="cart-title text-left">
                            <a href="{% url 'detail' item.product.slug %}" class="text-uppercase text-dark"><strong>{{ item.product.title }}</strong></a><br><span class="text-muted text-sm">Size: {{ item.size }}</span><br><span class="text-muted text-sm">Colour: {{ item.color }}</span>
                          </div>
                        </div>
                      </div>
                      <div class="col-2">{{ item.product.price }}</div>
                      <div class="col-2">
                        <div class="d-flex align-items-center">
                          <div class="btn btn-items btn-items-decrease click-decrease">-</div>
                          
                            <input type='hidden' name='pk' value='{{item.id}}' id='pk'>
                            <input type="text" name="qty" value="{{ item.quantity }}" class="form-control text-center input-items" id='quantity'>
                         
                          
                          <div class="btn btn-items btn-items-increase click-increase">+</div>
                        </div>
                      </div>
                      <div class="col-2 text-center">$<span id='line_total'>{{ item.line_total }}</span></div>
                      <div class="col-1 text-center"><a href="{% url 'remove_from_cart' item.id %}" class="cart-remove" id="{{item.id}}"><i class="material-icons delete-icon" id="{{item.id}}">delete_sweep</i></a></div>
                    </div>
                  </div>
                  <!-- Product-->
                  {% endfor %}
                  
                </div>
              </div>
            </div>
            <div class="my-5 d-flex justify-content-between flex-column flex-lg-row"><a href="category.html" class="btn btn-link text-muted"><i class="fa fa-chevron-left"></i> Continue Shopping</a><a href="{% url 'checkout' %}" class="btn btn-dark">Proceed to checkout <i class="fa fa-chevron-right"></i>                                                     </a></div>
          </div>
          <div class="col-lg-4">
            <div class="block mb-5">
              <div class="block-header">
                <h6 class="text-uppercase mb-0">Order Summary</h6>
              </div>
              <div class="block-body bg-light pt-1">
                <p class="text-sm">Shipping and additional costs are calculated based on values you have entered.</p>
                <ul class="order-summary mb-0 list-unstyled">
                  <li class="order-summary-item"><span>Order Subtotal </span><span>$<span id='cart_total' >{{ cart.total|floatformat:"-1" }}</span></span></li>
                  <li class="order-summary-item"><span>Shipping and handling</span><span>$10.00</span></li>
                  <li class="order-summary-item"><span>Tax</span><span>$0.00</span></li>
                  <li class="order-summary-item border-0"><span>Total</span><strong class="order-summary-total">$400.00</strong></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  {% else %}
  <!-- Hero Section-->
    <section class="hero">
      <div class="container">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb justify-content-center">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item active">Shopping cart        </li>
        </ol>

        <!-- Hero Content-->
        <div class="hero-content pb-5 text-center">
          <h1 class="hero-heading">Shopping cart</h1>
          <div class="row">   
            <div class="col-xl-8 offset-xl-2">
                <p class="lead text-muted">Your shopping cart is empty.</p>
            </div>
          </div>
        </div>

      </div>
    </section>
  {% endif %}

{% endblock content %}
{% block jquery %}
<script>
// ajax request function
  function ajax_call(number){
    var pk = $('#pk').val();
    var quantity = $('#quantity').val();

    // Calculate wheater it should increase or decrease the quantity
    if (number){
       var qty = Number(quantity) + number
    } else {
     var qty = quantity
    }
    console.log(pk, qty);
   

    $.ajax({
      type: "GET",
      url : "{% url 'update_cart_item' %}",
      data: {'pk': pk, 'qty': qty},
      success: function(data){
        console.log(data)
        $('#cart_total').text(data.cart_total)
        $('#line_total').text(data.line_total)
        if (data.product == 'empty'){
          //var item = 'item-' + data.id
          $('#item-'+data.id).remove()
        }

      },
     
    });
  }

  $('#quantity').change(function(){
    ajax_call();
  });

  $('.click-increase').click(function(){
    ajax_call(1);
  });
  $('.click-decrease').click(function(){
    ajax_call(-1);
  });

// Delete cart item using ajax request

{% comment %} $('.cart-remove').click(function(e){
  e.preventDefault();
  delete_cartitem_ajax($(this).attr("id"))
})

function delete_cartitem_ajax(value){
  var pk = value
  $.ajax({
    type: "GET",
    url: "{% url 'remove_from_cart' %}",
    data: {'pk': pk},
    success: function(data){
      console.log(data)
    },
    error: function(xhr,status,error){
      console.log(xhr,status,error);
    }

  });
};

  {% endcomment %}

//experiment successful
{% comment %} function experiment(value){
 console.log(value)
}

$(".delete-icon").click(function(){
  experiment($(this).attr('id'));
}) {% endcomment %}
 
</script>
{% endblock jquery %}

   